spring.application.name=spring-todo
#Conexión con la base de datos(Modo desarrollo)
#spring.datasource.url=jdbc:postgresql://localhost:5432/TaskManager
#spring.datasource.username=postgres-username
#spring.datasource.password=db-password
#spring.datasource.drive-class-name=org.postgresql.Driver

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.drive-class-name=org.postgresql.Driver

#Herramientas de desarrollo(modo desarrollo)
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#produccion:
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

server.port=8080
